### PR TITLE
Use F1 font for card headers

### PR DESCRIPTION
**Pull request by topscoder**
Cheers 🍻

### CODE REVIEW

**Comment by marcokreeft87** [comment]
Ah you made it work? Lets try it out 👍

**Comment by topscoder** [comment]
Scherm­afbeelding 2023-01-28 om 18 56 10

**Comment by marcokreeft87** [comment]
It was working for a second there but now its not working anymore :(

**Comment by topscoder** [comment]
Please check again :)

**Comment by marcokreeft87** [comment]
Yes this is working! I am currently working on the changes needed to make the unit tests working again

**Pull request merged**
