### PR TITLE
Added actions to cards with track layout

### PR DESCRIPTION
**Pull request by marcokreeft87**

### CODE REVIEW

**Comment by ChrisPolewiak** [comment]
> _ No description provided. _

Thanks for update... one question - can you add it to "card_type: countdown" too? Because it work only on "card_type: next_race"
Thanks in advance :-)

**Comment by marcokreeft87** [comment]
If you do show_raceinfo you will get a track layout with race info and a clickable image :)

**Comment by ChrisPolewiak** [comment]
Yes… but this is too large. Simple countdown looks better on my dashboard 😃

**Comment by marcokreeft87** [comment]
Gotcha, can you make a seperate change request otherwise I will forget

**Pull request merged**
